language: csharp
solution: Unosquare.Labs.EmbedIO.Lib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
matrix:
  include:
    - os: linux
      dotnet: 1.0.0-preview2-003131
      mono: latest
      dist: trusty
      sudo: false
    - os: osx
      dotnet: 1.0.0-preview2-003131
install:
  - dotnet restore
script:
  - dotnet build ./src/Unosquare.Swan -f netstandard1.6
  - dotnet test ./test/Unosquare.Swan.Test -f netcoreapp1.1
