version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#general'
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:  
       secure: FXRdP4yEISDEf2pIbbOZgm6mtXxm5hixHGSZCFEEANQIB2ltddAcINmNJX/LerbA

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
- mkdir tools
- nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools
build_script:
- dotnet build "src\Unosquare.Swan" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
test_script:
- tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"%ProgramFiles%\dotnet\dotnet.exe" -targetargs:"test test/Unosquare.Swan.Test -c %CONFIGURATION%" -output:coverage.xml -register:userdotnet
- tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoTokenVariable COVERALLS_REPO_TOKEN --commitId %APPVEYOR_REPO_COMMIT% --commitBranch %APPVEYOR_REPO_BRANCH% --commitAuthor %APPVEYOR_REPO_COMMIT_AUTHOR% --commitEmail %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL% --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%"
cache:
- '%USERPROFILE%\.nuget\packages'
